/**
 * generate_import_sql.js
 * Reads "Nova Lista de Estoque.xlsx" and outputs a ready-to-run SQL file
 * that inserts categories, subcategories, and products into Supabase.
 *
 * Usage:
 *   node execution/generate_import_sql.js
 *
 * Output:
 *   supabase/import_products.sql  (run this in Supabase SQL Editor)
 */

const XLSX = require("xlsx");
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const INPUT = path.join(ROOT, "Nova Lista de Estoque.xlsx");
const OUTPUT = path.join(ROOT, "supabase", "import_products.sql");

// ── Read spreadsheet ──────────────────────────────────────────────────────────
const wb = XLSX.readFile(INPUT);
const ws = wb.Sheets[wb.SheetNames[0]];
const rows = XLSX.utils.sheet_to_json(ws, { header: 1 });

// Skip header row, skip empty rows
const data = rows.slice(1).filter(
  (r) => r[0] != null && r[1] != null && r[2] != null
);

// ── Collect unique categories and subcategories ───────────────────────────────
const categories = [...new Set(data.map((r) => r[2]))];
const subcategories = [
  ...new Map(
    data.map((r) => [`${r[2]}|||${r[3]}`, { category: r[2], name: r[3] }])
  ).values(),
];

// ── Escape helper ─────────────────────────────────────────────────────────────
const esc = (s) => String(s ?? "").replace(/'/g, "''");

// ── Build SQL ─────────────────────────────────────────────────────────────────
const lines = [];

lines.push("-- ============================================================");
lines.push("-- Import: Products from Nova Lista de Estoque.xlsx");
lines.push("-- Generated by execution/generate_import_sql.js");
lines.push(`-- Generated at: ${new Date().toISOString()}`);
lines.push("-- Run in: Supabase Dashboard > SQL Editor");
lines.push("-- Run AFTER schema_reset_and_add_code.sql");
lines.push("-- ============================================================");
lines.push("");

// STEP 1 — Categories
lines.push("-- STEP 1: Insert categories");
for (const cat of categories) {
  lines.push(
    `INSERT INTO categories (name) VALUES ('${esc(cat)}') ON CONFLICT (name) DO NOTHING;`
  );
}
lines.push("");

// STEP 2 — Subcategories
lines.push("-- STEP 2: Insert subcategories");
for (const sub of subcategories) {
  lines.push(
    `INSERT INTO subcategories (category_id, name)` +
      ` SELECT id, '${esc(sub.name)}' FROM categories WHERE name = '${esc(sub.category)}'` +
      ` ON CONFLICT (category_id, name) DO NOTHING;`
  );
}
lines.push("");

// STEP 3 — Products
lines.push("-- STEP 3: Insert products");
for (const r of data) {
  const [code, name, category, subcategory, unit, min_stock] = r;
  lines.push(
    `INSERT INTO products (code, name, category, category_id, subcategory_id, unit, min_stock, current_stock)` +
      ` SELECT` +
      ` ${Number(code)},` +
      ` '${esc(name)}',` +
      ` '${esc(category)}',` +
      ` c.id,` +
      ` s.id,` +
      ` '${esc(unit)}',` +
      ` ${Number(min_stock) || 0},` +
      ` 0` +
      ` FROM categories c` +
      ` JOIN subcategories s ON s.category_id = c.id AND s.name = '${esc(subcategory)}'` +
      ` WHERE c.name = '${esc(category)}';`
  );
}
lines.push("");

// STEP 4 — Advance sequence past max code
const maxCode = Math.max(...data.map((r) => Number(r[0])));
lines.push("-- STEP 4: Advance sequence so next auto-code starts after the imported ones");
lines.push(`SELECT setval('products_code_seq', ${maxCode});`);
lines.push("");

lines.push("-- STEP 5 (verification)");
lines.push("-- SELECT code, name, category, unit FROM products ORDER BY code;");
lines.push(`-- SELECT COUNT(*) FROM products; -- expect ${data.length}`);

// ── Write output ──────────────────────────────────────────────────────────────
fs.writeFileSync(OUTPUT, lines.join("\n"), "utf8");
console.log(`✓ Generated: ${OUTPUT}`);
console.log(`  Categories : ${categories.length}`);
console.log(`  Subcategories: ${subcategories.length}`);
console.log(`  Products   : ${data.length}`);
console.log(`  Max code   : ${maxCode}`);
